//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int IdComponente { get; set; }
        public int IdCliente { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Componente Componente { get; set; }
        public virtual Componente Componente1 { get; set; }
    }
}
