//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configurador.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int idComponente { get; set; }
        public int idCliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> total { get; set; }
        public int id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Componente Componente { get; set; }
    }
}
